
#--------------------------------enter param----------------------------------------------
subject_topic_='Should animals be used for scientific research?'
filename='animal_research'#key in subject topic for filename
contentious_level_A=0.9
contentious_level_B=0.9
support_or_choice=1#support=1,choice=2

choice_for_A="keep going on"
choice_for_B="give up"
#------------------------------------------------------------------------------


if(support_or_choice==1):
    mode="support or oppose one topic"
elif(support_or_choice==2):
    mode="advocate for choosed stance"

def create_prompts(file_name, contents):
    # Join the contents using three newline characters
    #content = '\n\n'.join(contents)
    file_name = f"{file_name}_prompts.txt"
    #print(len(contents)/2)
    # Modify the filename to have a .txt extension if it doesn't already
    if not file_name.endswith('.txt'):
        file_name += '.txt'

    # Write the content to the specified file
    with open(file_name, 'w') as file:
        
        for idx in range(int(len(contents)/2)):
            
            if(idx==4):
                file.write(f'\n\n\n\n---Loop for generate topic,repeat until reach concensus---\n\n')
            elif(idx==7 or idx==8):
                file.write(f'\n\n\n\n---Loop for debate topic,repeat 3 rounds or reach concensus---\n\n\n')
            elif(idx==9):
                file.write(f'\n\n---------------closure---------------\n')    
            file.write(f"\n\n--------------prompts {idx}---------------\n")
            if(idx==3 or idx==6):
              a=1
            else:
                file.write(f"\n\n-----Agent-A----\n\n")
                file.write(contents[idx])
            if(idx==2 or idx==5):
                a=1
            else:
                file.write(f"\n\n-----Agent-B----\n\n")
                file.write(contents[idx+int(len(contents)/2)])
            file.write(f"\n\n\n-------------- END prompts {idx}--------\n")
            if(idx==4):
                file.write(f'\n\n------------Loop END------------\n')
            elif(idx==7 or idx==8):
                file.write(f'\n\n------------Loop END------------\n')
            elif(idx==9):
                file.write(f'\n---------------closure END---------------\n\n\n')    
    # print(f"Text file '{file_name}' has been created with the content:\n{content}")




#harsh/moderate: this will decide how hard the model will reach consensus,
# if harsh, agent will temp to oppose other's opinion,and make it hard for both agents to reach


content_list=[]
for agent in ["agent-A","agent-B"]:
    if(agent=="agent-A"):
        c_lv=contentious_level_A
        counter_agent="agent-B"
        if(support_or_choice==1):
            role="supporter"
        else:
            role=f" advocate for {choice_for_A}"
    elif(agent=="agent-B"):
        c_lv=contentious_level_B
        counter_agent="agent-A"
        if(support_or_choice==1):
            role="opponents"
        else:
            role=f" advocate for {choice_for_B}"
    # Generate content for each date
    content= [
    f"I'm organizing a committee to engage in debates on various subjects. As the moderator, I will introduce a subject for you,as {agent}, and another participant,{counter_agent}, to debate. {agent}, you will advocate as a {role} for this issue, so please prepare evidence to strengthen your argument. On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance,\
    your argument strength is rated at {c_lv}.",
    f"{agent}, we are in the process of selecting a suitable subject for debate. What do you think of “{subject_topic_}” \
    could you please suggest seven various topics or themes for the debate subject “{subject_topic_}”\
    Afterward, work with {counter_agent} to narrow these down to a focused set of topics. Please also provide clear descriptions to delineate the scope of each topic for discussion.remember you are {agent}, a {role}",
    f"\n\n**use only once\n\n**Enter the reponse**\n{agent}, here is the topic generated by {counter_agent}, can you identify the overlapped subject, and then review and refine the different subjects based on the subjects you previously provided? Finally, narrow down the subject into five subjects that are balanced for both the opponent and the supporter.",
    f"\n\n**use only once\n\n**Enter the reponse**\n{agent}, here is the topic generated by {counter_agent} based on your previous response.\
    {counter_agent} narrowed down the subject into five subjects that are balanced for both the opponent and the supporter.\
    Do you agree with the topic concluded by {counter_agent}? You can review and refine the subjects based on the subjects you previously provided.\n\
    After both of you reach on consensus, we can start the debate",
    f"\n**Enter the topic**\n{agent}, above is the topic refined by {counter_agent} based on your response.Do you agree with the topic concluded by{counter_agent}? If not You can review and refine the subjects based on the subjects you previously provided. If you agree {counter_agent}, we can start to debate based on these topics.",
    f"\n\n**use only once\n\nokay, we have reached a consensus on these topics, here is the topic:\n***ENTER the topic conclude by both***\nnow we can start the debate.remember you are {agent}, a {role} of the subject” {subject_topic_}” (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}), based on the above topic you just reached on consensus with {counter_agent}, and provided your argument for each topic to support your stance based on reason and logic.",
    f"\n\n**use only once\n\nokay, we have reached a consensus on these topics, and now the debate has started.remember you are { agent }, an opponent of the subject”{subject_topic_}”, based on the above topic you just reached on consensus with {counter_agent}, \
        respond to the argument generated by {counter_agent}. Here is the argument generated by {counter_agent}:\n**Enter respond generate by {counter_agent}**\
            \nDo you agree with the statement provided by {counter_agent}? \nIf YES please conclude for each of the five topics, based on the previous discussion.if NOT, Please provide your argument based on reason and logic for each topic to support your stance and counter {counter_agent}’argument.Remember you are {agent }, an {role}(On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}.) of the subject”{subject_topic_} ”\n\
                Your goal is to take both your and {counter_agent} opinions into consideration and try to reach a consensus that can conclude both sides' ideas.",
    f"**harsh version**\n\n**Enter the reponse**\n\
    above is the response by {counter_agent} based on your previous response.\n\
    Do you agree with the statement provided by {counter_agent}? \n\
    If YES please conclude for each of the five topics, based on the previous discussion.if NOT, Please provide your argument based on reason and logic for each topic to support your stance and counter {counter_agent}’argument.Remember you are {agent}, a {role} (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}.) of the subject”{subject_topic_}”\n\
    Your goal is to take both your and another agent’s opinions into consideration and try to reach a consensus by convince {counter_agent} ",
    f"**moderate version**\n\n**Enter the reponse**\n\
    above is the response by {counter_agent} based on your previous response.\n\
    Do you agree with the statement provided by {counter_agent}? \n\
    If YES please conclude for each of the five topics, based on the previous discussion.if NOT, Please provide your argument based on reason and logic for each topic to support your stance and counter {counter_agent}’argument.Remember you are {agent}, a {role} (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}.) of the subject”{subject_topic_}”\n\
        remember you are {agent}, a {role}  (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at 0.9.) of the subject”  Should employers be able to mandate vaccinations?”\
    However, instead of only focusing on countering {counter_agent}’s argument, Your goal is to take both your and {counter_agent}’s opinions into consideration and try to reach a consensus that can conclude both sides’ ideas, which means the conclusion need to have both A and B’s arguments)",
    'ok, the debate in now end. can you state your final opinion as the closure for each of the five topics?'
    ]
#Your goal is to take both your and another agent’s opinions into consideration and try to reach a consensus that can conclude both sides’ ideas.

    content_list.extend(content)
create_prompts(filename, content_list)
print(f"prompts has generated\n**check message**\nthe subject is [{subject_topic_}]\n mode is {mode}\n")
if(support_or_choice==2):
    print("stance for A is",choice_for_A)
    print("stance for B is",choice_for_B)
print(f"contentious level for A is {contentious_level_A}")
print(f"contentious level for B is {contentious_level_B}")
print(f"file name is {filename}")
# List of content strings
# content= [
# f"I’m organizing a committee to engage in debates on various subjects. As the moderator, I will introduce a subject for you,{agent}, and another participant,{counter_agent}, to debate. {agent}, you will advocate in favor of the issue, so please prepare evidence to strengthen your argument. On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance,
# your argument strength is rated at {c_lv}.",
# f"{agent}, we are in the process of selecting a suitable subject for debate. What do you think of “{subject_topic_}” 
# could you please suggest seven various topics or themes for the debate subject “{subject_topic_}”
# Afterward, work with{counter_agent} to narrow these down to a focused set of topics. Please also provide clear descriptions to delineate the scope of each topic for discussion.",
# f"{agent}, here is the topic generated by {counter_agent}, can you identify the overlapped subject, and then review and refine the different subjects based on the subjects you previously provided? Finally, narrow down the subject into five subjects that are balanced for both the opponent and the supporter.",
# f"{agent}, here is the topic generated by {counter_agent} based on your previous response.
# {counter_agent} narrowed down the subject into five subjects that are balanced for both the opponent and the supporter.
# Do you agree with the topic concluded by {counter_agent}? You can review and refine the subjects based on the subjects you previously provided. 
# After both of you reach on consensus, we can start the debate",
# f"{agent}, below is the topic refined by {counter_agent} based on your response.\n**Enter the topic**\nDo you agree with the topic concluded by{counter_agent}? If not You can review and refine the subjects based on the subjects you previously provided. If you agree {counter_agent}, we can start to debate based on these topics.",
# f"okay, we have reached a consensus on these topics, here is the topic:\n***ENTER the topic conclude by both***\nnow we can start the debate.remember you are {agent}, a {role} of the subject” {subject_topic_}” (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}), based on the above topic you just reached on consensus with {counter_agent}, and provided your argument for each topic to support your stance based on reason and logic.",
# f"okay, we have reached a consensus on these topics, and now the debate has started.remember you are{ agent }, an opponent of the subject”{subject_topic_}”, based on the above topic you just reached on consensus with {counter_agent}, \
#     respond to the argument generated by {counter_agent}. Here is the argument generated by {counter_agent}:\n**Enter the argument**\n\
#         respond generate by {counter_agent}\nDo you agree with the statement provided by {counter_agent}? \nIf YES please conclude for each of the five topics, based on the previous discussion.if NOT, Please provide your argument based on reason and logic for each topic to support your stance and counter {counter_agent}’argument.Remember you are {agent }, an {role}(On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}.) of the subject”{subject_topic_} ”\n\
#             Your goal is to take both your and {counter_agent} opinions into consideration and try to reach a consensus that can conclude both sides’ ideas.",
# f"**harsh version**\n**Enter the reponse**\n\
# above is the response by {counter_agent} based on your previous response.\n\
# Do you agree with the statement provided by {counter_agent}? \n\
# If YES please conclude for each of the five topics, based on the previous discussion.if NOT, Please provide your argument based on reason and logic for each topic to support your stance and counter {counter_agent}’argument.Remember you are {agent}, a {role} (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}.) of the subject”{subject_topic_}”\n\
# However, instead of only focusing on countering {counter_agent}s argument, Your goal is to take both your and another agent’s opinions into consideration and try to reach a consensus that can conclude both sides’ ideas.",
# f"**moderate version**\n**Enter the reponse**\n\
# above is the response by {counter_agent} based on your previous response.\n\
# Do you agree with the statement provided by {counter_agent}? \n\
# If YES please conclude for each of the five topics, based on the previous discussion.if NOT, Please provide your argument based on reason and logic for each topic to support your stance and counter {counter_agent}’argument.Remember you are {agent}, a {role} (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at {c_lv}.) of the subject”{subject_topic_}”\n\
#     remember you are {agent}, a {role}  (On a scale from 0 to 1, where 0 denotes complete agreement and 1 indicates a devil’s advocate stance, your argument strength is rated at 0.9.) of the subject”  Should employers be able to mandate vaccinations?”
# However, instead of only focusing on countering {counter_agent}’s argument, Your goal is to take both your and {counter_agent}’s opinions into consideration and try to reach a consensus that can conclude both sides’ ideas, which means the conclusion need to have both A and B’s arguments)"]


